/**
 * Generates a transaction receipt as a PNG image using Canvas API
 * and triggers a download in the browser.
 */
export function downloadReceipt(data: {
  txHash: string
  content: string // the message content with transaction details
  timestamp: number
}) {
  const canvas = document.createElement('canvas')
  const ctx = canvas.getContext('2d')
  if (!ctx) return

  const width = 600
  const padding = 40
  const lineHeight = 24
  const lines = data.content.split('\n').filter(l => l.trim())
  const height = 320 + lines.length * lineHeight

  canvas.width = width
  canvas.height = height

  // Background
  ctx.fillStyle = '#111827'
  ctx.fillRect(0, 0, width, height)

  // Border
  ctx.strokeStyle = '#10b981'
  ctx.lineWidth = 2
  ctx.strokeRect(1, 1, width - 2, height - 2)

  // Header bar
  ctx.fillStyle = '#10b981'
  ctx.fillRect(0, 0, width, 60)

  // Logo text
  ctx.fillStyle = '#ffffff'
  ctx.font = 'bold 24px monospace'
  ctx.fillText('ChainMate', padding, 40)

  ctx.font = '12px monospace'
  ctx.fillStyle = '#d1fae5'
  ctx.fillText('Transaction Receipt', width - padding - 140, 40)

  // Divider
  let y = 80

  // Date
  ctx.fillStyle = '#9ca3af'
  ctx.font = '13px monospace'
  ctx.fillText(`Date: ${new Date(data.timestamp).toLocaleString()}`, padding, y)
  y += 30

  // Network
  ctx.fillText('Network: BSC Testnet (Chain ID: 97)', padding, y)
  y += 30

  // Divider line
  ctx.strokeStyle = '#374151'
  ctx.lineWidth = 1
  ctx.beginPath()
  ctx.moveTo(padding, y)
  ctx.lineTo(width - padding, y)
  ctx.stroke()
  y += 20

  // Transaction details
  ctx.fillStyle = '#f3f4f6'
  ctx.font = '14px monospace'
  for (const line of lines) {
    // Strip emoji for cleaner rendering (canvas doesn't render all emoji well)
    const cleanLine = line.replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/gu, '').trim()
    if (!cleanLine) continue

    // Highlight "Tx Hash:" line
    if (cleanLine.toLowerCase().includes('tx hash')) {
      ctx.fillStyle = '#10b981'
      ctx.font = 'bold 13px monospace'
    } else {
      ctx.fillStyle = '#f3f4f6'
      ctx.font = '14px monospace'
    }

    // Word wrap long lines
    const maxWidth = width - padding * 2
    if (ctx.measureText(cleanLine).width > maxWidth) {
      const mid = Math.floor(cleanLine.length / 2)
      ctx.fillText(cleanLine.slice(0, mid), padding, y)
      y += lineHeight
      ctx.fillText(cleanLine.slice(mid), padding, y)
    } else {
      ctx.fillText(cleanLine, padding, y)
    }
    y += lineHeight
  }

  y += 10

  // Divider
  ctx.strokeStyle = '#374151'
  ctx.beginPath()
  ctx.moveTo(padding, y)
  ctx.lineTo(width - padding, y)
  ctx.stroke()
  y += 25

  // BscScan link
  ctx.fillStyle = '#60a5fa'
  ctx.font = '12px monospace'
  ctx.fillText(`View on BscScan:`, padding, y)
  y += 18
  ctx.fillStyle = '#93c5fd'
  ctx.font = '11px monospace'
  ctx.fillText(`https://testnet.bscscan.com/tx/${data.txHash}`, padding, y)
  y += 30

  // Footer
  ctx.fillStyle = '#6b7280'
  ctx.font = '11px monospace'
  ctx.fillText('Generated by ChainMate - AI Crypto Companion for BNB Chain', padding, y)

  // Download
  canvas.toBlob((blob) => {
    if (!blob) return
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `chainmate-receipt-${data.txHash.slice(0, 10)}.png`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }, 'image/png')
}
